export const materialData = {
  categories: [
    { id: 1, name: "Conduit and Fittings" },
    { id: 2, name: "Wire and Cable" },
    { id: 3, name: "Outlet Boxes" },
    { id: 4, name: "Lighting Fixtures" },
    { id: 5, name: "Wiring Devices" },
    { id: 6, name: "Service Entrance Equipment" },
    { id: 7, name: "Underfloor Raceway" },
    { id: 8, name: "Bus Duct" },
    { id: 9, name: "Cable Tray" },
    { id: 10, name: "Signal Systems" },
    { id: 11, name: "Precast Concrete Access Boxes" },
    { id: 12, name: "Equipment Hook Up" },
    { id: 13, name: "Motor Control Equipment" },
    { id: 14, name: "Trenching and Excavation" },
    { id: 15, name: "Surface Raceways" },
    { id: 16, name: "Grounding" },
    { id: 17, name: "Assemblies" },
    { id: 18, name: "Communications" },
    { id: 19, name: "Undercarpet Wiring Systems" },
    { id: 20, name: "Circuit Breakers" },
  ],
  materials: {
    1: [
      {
        id: "1-1",
        name: '1/2" EMT Conduit',
        size: '1/2"',
        type: "EMT",
        unit: "LF",
        manhourUnit: 0.083,
      },
      // Add more conduit materials here
    ],
    2: [
      {
        id: "2-1",
        name: "THW 600V Solid Copper #14",
        size: "#14",
        type: "THW 600V Solid",
        unit: "KLF",
        manhourUnit: 6,
      },
      {
        id: "2-2",
        name: "THW 600V Solid Copper #12",
        size: "#12",
        type: "THW 600V Solid",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-3",
        name: "THW 600V Solid Copper #10",
        size: "#10",
        type: "THW 600V Solid",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-4",
        name: "THW 600V Stranded Copper #14",
        size: "#14",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 6,
      },
      {
        id: "2-5",
        name: "THW 600V Stranded Copper #12",
        size: "#12",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-6",
        name: "THW 600V Stranded Copper #10",
        size: "#10",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-7",
        name: "THW 600V Stranded Copper #8",
        size: "#8",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 9,
      },
      {
        id: "2-8",
        name: "THW 600V Stranded Copper #6",
        size: "#6",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 10,
      },
      {
        id: "2-9",
        name: "THW 600V Stranded Copper #4",
        size: "#4",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 12,
      },
      {
        id: "2-10",
        name: "THW 600V Stranded Copper #2",
        size: "#2",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 13,
      },
      {
        id: "2-11",
        name: "THW 600V Stranded Copper #1",
        size: "#1",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 14,
      },
      {
        id: "2-12",
        name: "THW 600V Stranded Copper #1/0",
        size: "#1/0",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 15,
      },
      {
        id: "2-13",
        name: "THW 600V Stranded Copper #2/0",
        size: "#2/0",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 16,
      },
      {
        id: "2-14",
        name: "THW 600V Stranded Copper #3/0",
        size: "#3/0",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 17,
      },
      {
        id: "2-15",
        name: "THW 600V Stranded Copper #4/0",
        size: "#4/0",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 18,
      },
      {
        id: "2-16",
        name: "THW 600V Stranded Copper #250 KCMIL",
        size: "#250 KCMIL",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 20,
      },
      {
        id: "2-17",
        name: "THW 600V Stranded Copper #300 KCMIL",
        size: "#300 KCMIL",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 23,
      },
      {
        id: "2-18",
        name: "THW 600V Stranded Copper #350 KCMIL",
        size: "#350 KCMIL",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 24,
      },
      {
        id: "2-19",
        name: "THW 600V Stranded Copper #400 KCMIL",
        size: "#400 KCMIL",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 25,
      },
      {
        id: "2-20",
        name: "THW 600V Stranded Copper #500 KCMIL",
        size: "#500 KCMIL",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 26,
      },
      {
        id: "2-21",
        name: "THW 600V Stranded Copper #600 KCMIL",
        size: "#600 KCMIL",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 30,
      },
      {
        id: "2-22",
        name: "THW 600V Stranded Copper #750 KCMIL",
        size: "#750 KCMIL",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 30,
      },
      {
        id: "2-23",
        name: "THW 600V Stranded Copper #1000 KCMIL",
        size: "#1000 KCMIL",
        type: "THW 600V Stranded",
        unit: "KLF",
        manhourUnit: 32,
      },
      {
        id: "2-24",
        name: "THHN 600V Solid Copper #14",
        size: "#14",
        type: "THHN 600V Solid",
        unit: "KLF",
        manhourUnit: 6,
      },
      {
        id: "2-25",
        name: "THHN 600V Solid Copper #12",
        size: "#12",
        type: "THHN 600V Solid",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-26",
        name: "THHN 600V Solid Copper #10",
        size: "#10",
        type: "THHN 600V Solid",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-44",
        name: "THHW 600V Solid Copper #14",
        size: "#14",
        type: "THHW 600V Solid",
        unit: "KLF",
        manhourUnit: 6,
      },
      {
        id: "2-45",
        name: "THHW 600V Solid Copper #12",
        size: "#12",
        type: "THHW 600V Solid",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-46",
        name: "THHW 600V Solid Copper #10",
        size: "#10",
        type: "THHW 600V Solid",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-67",
        name: "USE, RHH-RHW 600V Solid Copper #12",
        size: "#12",
        type: "USE, RHH-RHW 600V Solid",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-68",
        name: "USE, RHH-RHW 600V Solid Copper #10",
        size: "#10",
        type: "USE, RHH-RHW 600V Solid",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-90",
        name: "MTW 600V 90° Stranded Copper #18",
        size: "#18",
        type: "MTW 600V 90° Stranded",
        unit: "KLF",
        manhourUnit: 5,
      },
      {
        id: "2-91",
        name: "MTW 600V 90° Stranded Copper #16",
        size: "#16",
        type: "MTW 600V 90° Stranded",
        unit: "KLF",
        manhourUnit: 5.5,
      },
      {
        id: "2-96",
        name: "TFFN 600V 90° Stranded Copper #18, 16 Strand",
        size: "#18",
        type: "TFFN 600V 90° Stranded",
        unit: "KLF",
        manhourUnit: 5,
      },
      {
        id: "2-97",
        name: "TFFN 600V 90° Stranded Copper #16, 26 Strand",
        size: "#16",
        type: "TFFN 600V 90° Stranded",
        unit: "KLF",
        manhourUnit: 5.5,
      },
      {
        id: "2-98",
        name: "AWM 1000V 90° Copper #14, 19 Strand",
        size: "#14",
        type: "AWM 1000V 90°",
        unit: "KLF",
        manhourUnit: 5,
      },
      {
        id: "2-105",
        name: "SJ 300V 60° Flexible Cord #18-2",
        size: "#18-2",
        type: "SJ 300V 60°",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-129",
        name: "S 600V 60° Flexible Cord #18-2",
        size: "#18-2",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-130",
        name: "S 600V 60° Flexible Cord #16-2",
        size: "#16-2",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 9,
      },
      {
        id: "2-131",
        name: "S 600V 60° Flexible Cord #14-2",
        size: "#14-2",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 10,
      },
      {
        id: "2-132",
        name: "S 600V 60° Flexible Cord #12-2",
        size: "#12-2",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 12,
      },
      {
        id: "2-133",
        name: "S 600V 60° Flexible Cord #10-2",
        size: "#10-2",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 14,
      },
      {
        id: "2-134",
        name: "S 600V 60° Flexible Cord #18-3",
        size: "#18-3",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 8.25,
      },
      {
        id: "2-135",
        name: "S 600V 60° Flexible Cord #16-3",
        size: "#16-3",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 9.25,
      },
      {
        id: "2-136",
        name: "S 600V 60° Flexible Cord #14-3",
        size: "#14-3",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 10.3,
      },
      {
        id: "2-137",
        name: "S 600V 60° Flexible Cord #12-3",
        size: "#12-3",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 12.3,
      },
      {
        id: "2-138",
        name: "S 600V 60° Flexible Cord #10-3",
        size: "#10-3",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 14.3,
      },
      {
        id: "2-139",
        name: "S 600V 60° Flexible Cord #18-4",
        size: "#18-4",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 8.5,
      },
      {
        id: "2-140",
        name: "S 600V 60° Flexible Cord #16-4",
        size: "#16-4",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 9.5,
      },
      {
        id: "2-141",
        name: "S 600V 60° Flexible Cord #14-4",
        size: "#14-4",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 10.5,
      },
      {
        id: "2-142",
        name: "S 600V 60° Flexible Cord #12-4",
        size: "#12-4",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 12.5,
      },
      {
        id: "2-143",
        name: "S 600V 60° Flexible Cord #10-4",
        size: "#10-4",
        type: "S 600V 60°",
        unit: "KLF",
        manhourUnit: 14.5,
      },
      {
        id: "2-144",
        name: "SJTO 300V 60° Flexible Yellow Cord #18-2",
        size: "#18-2",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-145",
        name: "SJTO 300V 60° Flexible Yellow Cord #16-2",
        size: "#16-2",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 9,
      },
      {
        id: "2-146",
        name: "SJTO 300V 60° Flexible Yellow Cord #14-2",
        size: "#14-2",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 10,
      },
      {
        id: "2-147",
        name: "SJTO 300V 60° Flexible Yellow Cord #18-3",
        size: "#18-3",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 8.25,
      },
      {
        id: "2-148",
        name: "SJTO 300V 60° Flexible Yellow Cord #16-3",
        size: "#16-3",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 9.25,
      },
      {
        id: "2-149",
        name: "SJTO 300V 60° Flexible Yellow Cord #14-3",
        size: "#14-3",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 10.3,
      },
      {
        id: "2-150",
        name: "SJTO 300V 60° Flexible Yellow Cord #18-4",
        size: "#18-4",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 8.5,
      },
      {
        id: "2-151",
        name: "SJTO 300V 60° Flexible Yellow Cord #16-4",
        size: "#16-4",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 9.5,
      },
      {
        id: "2-152",
        name: "SJTO 300V 60° Flexible Yellow Cord #14-4",
        size: "#14-4",
        type: "SJTO 300V 60°",
        unit: "KLF",
        manhourUnit: 10.5,
      },
      {
        id: "2-153",
        name: "STO 300V 60° Flexible Yellow Cord #18-2",
        size: "#18-2",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 8,
      },
      {
        id: "2-154",
        name: "STO 300V 60° Flexible Yellow Cord #16-2",
        size: "#16-2",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 9,
      },
      {
        id: "2-155",
        name: "STO 300V 60° Flexible Yellow Cord #14-2",
        size: "#14-2",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 10,
      },
      {
        id: "2-156",
        name: "STO 300V 60° Flexible Yellow Cord #12-2",
        size: "#12-2",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 12,
      },
      {
        id: "2-157",
        name: "STO 300V 60° Flexible Yellow Cord #10-2",
        size: "#10-2",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 14,
      },
      {
        id: "2-158",
        name: "STO 300V 60° Flexible Yellow Cord #18-3",
        size: "#18-3",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 8.25,
      },
      {
        id: "2-159",
        name: "STO 300V 60° Flexible Yellow Cord #16-3",
        size: "#16-3",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 9.25,
      },
      {
        id: "2-160",
        name: "STO 300V 60° Flexible Yellow Cord #14-3",
        size: "#14-3",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 10.3,
      },
      {
        id: "2-161",
        name: "STO 300V 60° Flexible Yellow Cord #12-3",
        size: "#12-3",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 12.3,
      },
      {
        id: "2-162",
        name: "STO 300V 60° Flexible Yellow Cord #10-3",
        size: "#10-3",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 14.3,
      },
      {
        id: "2-163",
        name: "STO 300V 60° Flexible Yellow Cord #18-4",
        size: "#18-4",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 8.5,
      },
      {
        id: "2-164",
        name: "STO 300V 60° Flexible Yellow Cord #16-4",
        size: "#16-4",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 9.5,
      },
      {
        id: "2-165",
        name: "STO 300V 60° Flexible Yellow Cord #14-4",
        size: "#14-4",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 10.5,
      },
      {
        id: "2-166",
        name: "STO 300V 60° Flexible Yellow Cord #12-4",
        size: "#12-4",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 12.5,
      },
      {
        id: "2-167",
        name: "STO 300V 60° Flexible Yellow Cord #10-4",
        size: "#10-4",
        type: "STO 300V 60°",
        unit: "KLF",
        manhourUnit: 14.5,
      },
      {
        id: "2-168",
        name: "Type W 600V Portable Power Cable #8-2",
        size: "#8-2",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 9,
      },
      {
        id: "2-169",
        name: "Type W 600V Portable Power Cable #6-2",
        size: "#6-2",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 10,
      },
      {
        id: "2-170",
        name: "Type W 600V Portable Power Cable #4-2",
        size: "#4-2",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 11,
      },
      {
        id: "2-171",
        name: "Type W 600V Portable Power Cable #2-2",
        size: "#2-2",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 12,
      },
      {
        id: "2-172",
        name: "Type W 600V Portable Power Cable #1-2",
        size: "#1-2",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 13,
      },
      {
        id: "2-173",
        name: "Type W 600V Portable Power Cable #8-3",
        size: "#8-3",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 9.25,
      },
      {
        id: "2-174",
        name: "Type W 600V Portable Power Cable #6-3",
        size: "#6-3",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 10.3,
      },
      {
        id: "2-175",
        name: "Type W 600V Portable Power Cable #4-3",
        size: "#4-3",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 11.3,
      },
      {
        id: "2-176",
        name: "Type W 600V Portable Power Cable #2-3",
        size: "#2-3",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 12.3,
      },
      {
        id: "2-177",
        name: "Type W 600V Portable Power Cable #1-3",
        size: "#1-3",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 13.3,
      },
      {
        id: "2-178",
        name: "Type W 600V Portable Power Cable #8-4",
        size: "#8-4",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 9.5,
      },
      {
        id: "2-179",
        name: "Type W 600V Portable Power Cable #6-4",
        size: "#6-4",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 10.5,
      },
      {
        id: "2-180",
        name: "Type W 600V Portable Power Cable #4-4",
        size: "#4-4",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 11.5,
      },
      {
        id: "2-181",
        name: "Type W 600V Portable Power Cable #2-4",
        size: "#2-4",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 12.5,
      },
      {
        id: "2-182",
        name: "Type W 600V Portable Power Cable #1-4",
        size: "#1-4",
        type: "Type W 600V Portable Power Cable",
        unit: "KLF",
        manhourUnit: 13.5,
      },
      {
        id: "2-183",
        name: "Type NM 600V Cable (Romex) Without Ground #14-2",
        size: "#14-2",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 6,
      },
      {
        id: "2-184",
        name: "Type NM 600V Cable (Romex) Without Ground #12-2",
        size: "#12-2",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 6.5,
      },
      {
        id: "2-185",
        name: "Type NM 600V Cable (Romex) Without Ground #10-2",
        size: "#10-2",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-186",
        name: "Type NM 600V Cable (Romex) Without Ground #14-3",
        size: "#14-3",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 6.5,
      },
      {
        id: "2-187",
        name: "Type NM 600V Cable (Romex) Without Ground #12-3",
        size: "#12-3",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-188",
        name: "Type NM 600V Cable (Romex) Without Ground #10-3",
        size: "#10-3",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 7.5,
      },
      {
        id: "2-189",
        name: "Type NM 600V Cable (Romex) Without Ground #8-3",
        size: "#8-3",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 10,
      },
      {
        id: "2-190",
        name: "Type NM 600V Cable (Romex) Without Ground #6-3",
        size: "#6-3",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 14,
      },
      {
        id: "2-191",
        name: "Type NM 600V Cable (Romex) Without Ground #4-3",
        size: "#4-3",
        type: "Type NM 600V Cable (Romex) Without Ground",
        unit: "KLF",
        manhourUnit: 16,
      },
      {
        id: "2-192",
        name: "Type NM 600V Cable (Romex) With Ground #14-2",
        size: "#14-2",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 6,
      },
      {
        id: "2-193",
        name: "Type NM 600V Cable (Romex) With Ground #12-2",
        size: "#12-2",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 6.5,
      },
      {
        id: "2-194",
        name: "Type NM 600V Cable (Romex) With Ground #10-2",
        size: "#10-2",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-195",
        name: "Type NM 600V Cable (Romex) With Ground #8-2",
        size: "#8-2",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 9,
      },
      {
        id: "2-196",
        name: "Type NM 600V Cable (Romex) With Ground #6-2",
        size: "#6-2",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 12,
      },
      {
        id: "2-197",
        name: "Type NM 600V Cable (Romex) With Ground #14-3",
        size: "#14-3",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 6.5,
      },
      {
        id: "2-198",
        name: "Type NM 600V Cable (Romex) With Ground #12-3",
        size: "#12-3",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 7,
      },
      {
        id: "2-199",
        name: "Type NM 600V Cable (Romex) With Ground #10-3",
        size: "#10-3",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 7.5,
      },
      {
        id: "2-200",
        name: "Type NM 600V Cable (Romex) With Ground #8-3",
        size: "#8-3",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 10,
      },
      {
        id: "2-201",
        name: "Type NM 600V Cable (Romex) With Ground #6-3",
        size: "#6-3",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 14,
      },
      {
        id: "2-202",
        name: "Type NM 600V Cable (Romex) With Ground #4-3",
        size: "#4-3",
        type: "Type NM 600V Cable (Romex) With Ground",
        unit: "KLF",
        manhourUnit: 16,
      },
    ],
    3: [
      // Outlet Boxes materials go here
    ],
    // ...Add materials for the rest of the categories
    20: [
      {
        id: "breaker-1p-10a",
        name: "1 Pole 10A Circuit Breaker",
        size: "10A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-15a",
        name: "1 Pole 15A Circuit Breaker",
        size: "15A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-20a",
        name: "1 Pole 20A Circuit Breaker",
        size: "20A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-25a",
        name: "1 Pole 25A Circuit Breaker",
        size: "25A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-30a",
        name: "1 Pole 30A Circuit Breaker",
        size: "30A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-35a",
        name: "1 Pole 35A Circuit Breaker",
        size: "35A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-40a",
        name: "1 Pole 40A Circuit Breaker",
        size: "40A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-45a",
        name: "1 Pole 45A Circuit Breaker",
        size: "45A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-50a",
        name: "1 Pole 50A Circuit Breaker",
        size: "50A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-60a",
        name: "1 Pole 60A Circuit Breaker",
        size: "60A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
      {
        id: "breaker-1p-70a",
        name: "1 Pole 70A Circuit Breaker",
        size: "70A",
        type: "1 Pole",
        unit: "EA",
        manhourUnit: 0.1,
      },
    ],
  },
}
